### ISSUE TITLE
Support for page category on homepage

### ISSUE THREAD

**Issue by fxbenard** [hexagone-io/hexagone-nantes#6]
For now we can only add "pages", we'll it be possible to add "category archive pages"...

**Comment by devinsays** [comment]
Started working on this, and then got distracted by a small core inconsistency.

The only solution I can really think of is to add and text option to the customizer under every page that with an optional URL link. However, that makes the Customizer much more full and I'm not sure how many people would use it.

What do you think?

**Comment by fxbenard** [comment]
Thanks for looking at that.

Let's keep it simple, don't overload the customizer. Let's forget about that feature.
