### ISSUE TITLE
Site logo image not set on https

### ISSUE THREAD

**Issue by fxbenard** [hexagone-io/hexagone-nantes#7]
The logo image is set in http

**Comment by devinsays** [comment]
This is a problem with our multisite install.

**Comment by fxbenard** [comment]
Ok it will not happen on our users site then.

**Comment by devinsays** [comment]
No, it uses the URL from the media uploader.

I just installed the WordPress HTTPS plugin and activated for all our sites. New sites should also get set to SSL by default.

This appears to have resolved the issue.

**Comment by fxbenard** [comment]
All demos sites are down for me!


Le 10/07/2015 00:02, Devin Price a écrit :
>
> Closed #7 <https://github.com/hexagone-io/hexagone-nantes/issues/7>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/hexagone-io/hexagone-nantes/issues/7#event-352377652>.
>

-- 
signature FX Bénard | FxB
WP[i18n] & FR[l10n] - What else
Twitter : @fxbenard <https://twitter.com/fxbenard>
Google+ : Fx Bénard <https://plus.google.com/115184248259085010066/posts>
Transifex : fxbenard <https://www.transifex.com/accounts/profile/fxbenard/>

**Comment by devinsays** [comment]
Ug, I hate dealing with all this ngnix server config stuff. Deactivated the plugin. I'll try to tackle it again when I have more energy for it.
